### ISSUE TITLE
Integrate Django models for the Worklists, patients and studies as apps

### ISSUE THREAD

**Issue by Karelger** [comic/grand-challenge.org#570]
A separate Django app has been developed to prototype an API that offers basic patient and study information, sorted and organized through worklist nodes. This should be converted to apps that can be utilized in a less specific use case than serving as an information source for the ASAP worklist interface.

**Requirements**
- Translate prototype to several decoupled apps
- Allow for a more generic way to couple the information

**Tasks**
- [x] API
  - [x] Convert Patient information to standalone app
  - [x] Convert Study information to standalone app
  - [x] Convert Worklist information to standalone app
  - [ ] Create a pathology app that connects the information of the three standalone models
- [x] UI
  - [x] Implement UI for CRUD of Patient objects
  - [x] Implement UI for CRUD of Study objects
  - [x] Implement UI for CRUD of Worklist objects

**Comment by Karelger** [comment]
Since the Worklists require a tree structure, mptt might be a better route to take, rather than implementing some custom tree model. The Worklist app will also become standalone, with an overarching pathology app connecting the three.

**Comment by Karelger** [comment]
Pathology API is complete, and the three base apps all have an API and UI to edit these elements. These might still receive refinements though. But tickets will be made when that happens.
