### ISSUE TITLE
Add comment field and comment annotation model

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#845]
The graders want the ability to add an image specific comment to annotate abnormalities that cannot be described by annotating a lesion. I will add an image specific annotation model with a text field to the back-end and a textbox in the front-end that allows the graders to type additional comments while annotating an image.

**Tasks**
- [x] Add comment annotation model
- [x] Add route and APIView for this model
- [x] Add tests
- [x] Add textbox in front-end and autosave comment on edit
